### ISSUE TITLE
Fixing something

### ISSUE THREAD

**Issue by lopestom** [ZunayedDihan/android_device_infinix_X6827#2]
So I made some minimals changes to more tests. Bu I have other ideia about https://dumps.tadiphone.dev/dumps/infinix/infinix-x6827/-/blob/sys_tssi_64_infinix-user-12-SP1A.210812.016-289671-release-keys/bootimg/01_dtbdump_MT6781.dtb
This is only for remenber if others tests not helped.

Th img compiling now: https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/4984558247/jobs/8923047066

**Comment by lopestom** [comment]
New boot.img compiled: https://github.com/lopestom/Action-Recovery-Builder-CT/releases/download/4984558247/boot.img

After this new test so here's final help.

Good Luck

Cheers.

**Comment by lopestom** [comment]
> I modified the twrp of the infinix note 12 device

What's your device?
Infinix 
Note 12 - X663D
Note 12 G96 / Turbo - X670
Note 12 VIP - X672
Note 12S (12) - X663?? - G88 - A11
Note 12 Pro - X676B
Note 12 5G - X671
Note 12 Pro 5G - X671B

**Comment by ZunayedDihan** [comment]
Is he still in the discussion?

**Comment by lopestom** [comment]
> Is he still in the discussion?

If he want so we see answer of him.

**Comment by ZunayedDihan** [comment]
Hi i followed this procedure

Install the boot.img

fastboot flashing unlock_critical

Use stock vbmeta or modified vbmeta file [preferencial]


Still bootloop

**Comment by lopestom** [comment]
> Hi i followed this procedure
> 
> Install the boot.img
> 
> fastboot flashing unlock_critical
> 
> Use stock vbmeta or modified vbmeta file [preferencial]
> 
> Still bootloop

First `fastboot flashing unlock_critical`
reboot device without settings anything!
reboot to fastboot and install stock vbmeta.img file - install twrp.img
no good.

reboot to fastboot and install modified vbmeta.img file - install twrp.img
no good.

try
```
fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta_system.img
fastboot --disable-verity --disable-verification flash vbmeta vbmeta_vendor.img
```
with stock vbmeta and modified vbmeta file.

install twrp.img
`fastboot reboot recovery`

**Comment by ZunayedDihan** [comment]
Okey got it lemme try

**Comment by lopestom** [comment]
2 weeks..... Closed without feedback!.
